inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/'
    - 'spec/**/**'
    - 'stage/**/**'

Style/FrozenStringLiteralComment:
  Enabled: false
