inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/'
    - 'spec/**/**'
    - 'stage/**/**'
    - '.rubocop_todo.yml'
    - '.rubocop.yml'

Style/FrozenStringLiteralComment:
  Enabled: false
