default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: amphitheatre_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: amphitheatre_test
  pool: 5

production:
  <<: *default
  database: amphitheatre_production
  username: amphitheatre
  password: <%= ENV['AMPHITHEATRE_DATABASE_PASSWORD'] %>

ci:
  <<: *test
  username: postgres
